// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC68KLMovBYZve8vN2AUpeJ87gghD3RiZY',
    appId: '1:185388272551:web:13880b205c54bdf7d00482',
    messagingSenderId: '185388272551',
    projectId: 'emotai123',
    authDomain: 'emotai123.firebaseapp.com',
    storageBucket: 'emotai123.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCcMy4I0ccPxlAzxi8IeukMUvb8HuvSLvo',
    appId: '1:185388272551:android:493470252ea8b0ded00482',
    messagingSenderId: '185388272551',
    projectId: 'emotai123',
    storageBucket: 'emotai123.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyATB47LYdRwToD-hr5ThFVB067eQp-emXI',
    appId: '1:185388272551:ios:7591bcbaa2133155d00482',
    messagingSenderId: '185388272551',
    projectId: 'emotai123',
    storageBucket: 'emotai123.firebasestorage.app',
    iosBundleId: 'com.example.emotai',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyATB47LYdRwToD-hr5ThFVB067eQp-emXI',
    appId: '1:185388272551:ios:7591bcbaa2133155d00482',
    messagingSenderId: '185388272551',
    projectId: 'emotai123',
    storageBucket: 'emotai123.firebasestorage.app',
    iosBundleId: 'com.example.emotai',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC68KLMovBYZve8vN2AUpeJ87gghD3RiZY',
    appId: '1:185388272551:web:66bcb11edae8d77cd00482',
    messagingSenderId: '185388272551',
    projectId: 'emotai123',
    authDomain: 'emotai123.firebaseapp.com',
    storageBucket: 'emotai123.firebasestorage.app',
  );
}
